import weaviate
import os
import json
from dotenv import load_dotenv

load_dotenv()

def inspect_db():
    client = weaviate.connect_to_local(
        headers={"X-OpenAI-Api-Key": os.getenv("OPENAI_API_KEY")}
    )
    
    try:
        collection_name = "EQxReport"
        if not client.collections.exists(collection_name):
            print(f"Collection '{collection_name}' does not exist.")
            return

        collection = client.collections.get(collection_name)

        # 1. Fetch a sample of objects (e.g., 20)
        # We fetch metadata=True to see creation times etc if needed
        response = collection.query.fetch_objects(
            limit=5,
            return_properties=[
                "country", "iso_code", "income_group", 
                "eqx_rank", "eqx_year", "summary", 
                "themes", "other_countries_mentioned",
                "chunk_index", "total_chunks", "text"
            ]
        )

        if not response.objects:
            print("Database is empty.")
            return

        print(f"\n--- Found {len(response.objects)} sample objects ---\n")

        # Group by country to avoid spamming 10 chunks from the same file
        seen_countries = set()

        for obj in response.objects:
            props = obj.properties
            country = props.get("country")

            if country in seen_countries:
                continue
            
            seen_countries.add(country)

            print(f"=== INSPECTION: {country} ===")
            
            # 1. METADATA
            meta_view = {
                "ISO": props.get("iso_code"),
                "Region": props.get("region"),
                "Income Group": props.get("income_group"),
                "Rank": props.get("eqx_rank"),
                "Year": props.get("eqx_year"),
                "Mentions": props.get("other_countries_mentioned"),
                "Themes": props.get("themes")
            }
            print(f" Metadata:\n{json.dumps(meta_view, indent=2)}")

            # 2. SUMMARY (Generated by AI)
            print(f"\n AI Summary of Document:\n{props.get('summary')}")

            # 3. CHUNK INFO
            print(f"\n Text Chunk ({props.get('chunk_index')}/{props.get('total_chunks')}):")
            # Print first 200 chars only to keep it readable
            preview_text = props.get('text', '')[:200].replace('\n', ' ')
            print(f"\"{preview_text}...\"\n")
            print("-" * 60 + "\n")

    finally:
        client.close()

if __name__ == "__main__":
    inspect_db()